include: package:very_good_analysis/analysis_options.yaml

analyzer:
  errors:
    lines_longer_than_80_chars: ignore
  exclude:
    - "lib/src/**/*.g.dart"
    - "lib/src/**/*.freezed.dart"
    - "lib/src/ui/l10n/*.dart"