name: Fetch Firmware Versions
description: Clones the firmware repo and extracts available tags.
outputs:
  versions:
    description: JSON array of firmware tags
    value: ${{ steps.set-output.outputs.versions }}
runs:
  using: "composite"
  steps:
    - name: Fetch firmware tags
      id: set-output
      shell: bash
      run: |
        git clone --quiet --depth=1 --filter=blob:none --no-checkout https://github.com/merckgroup/mtrust-device-sim.git repo
        cd repo
        git fetch --tags --quiet
        tags=$(git tag -l | jq -R . | jq -s .)
        echo "Available firmware versions: $tags"
        echo "versions=$tags" >> $GITHUB_OUTPUT
        