name: Dev - 🚧 build package

on:
  push:
    branches:
      - dev

jobs:
  validate:
    name: Validate Package
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1

      - name: Prepare Flutter
        uses: emdgroup/mtrust-urp/.github/shared_actions/prepare-flutter@dev
        with:
          directory: "."

      - name: Validate Flutter
        uses: emdgroup/mtrust-urp/.github/shared_actions/validate-flutter@dev
        with:
          directory: "."
          is_package: true

      - name: Check licenses
        uses: emdgroup/mtrust-urp/.github/shared_actions/check-dart-licenses@dev
        with:
          directory: "."

  api-guard:
    needs: validate
    uses: emdgroup/mtrust-api-guard/.github/workflows/publish_workflow.yaml@main
    with:
      git_push_branch: dev
      git_push: true
      pre_release: true
    secrets: inherit
