name: Main - 🚀 build package

on:
  push:
    branches:
      - main

jobs:
  validate:
    name: Validate Package
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1

      - name: Prepare Flutter
        uses: emdgroup/mtrust-urp/.github/shared_actions/prepare-flutter@main
        with:
          directory: "."

      - name: Validate Flutter
        uses: emdgroup/mtrust-urp/.github/shared_actions/validate-flutter@main
        with:
          directory: "."
          is_package: true

      - name: Check licenses
        uses: emdgroup/mtrust-urp/.github/shared_actions/check-dart-licenses@main
        with:
          directory: "."

  api-guard:
    needs: validate
    uses: emdgroup/mtrust-api-guard/.github/workflows/publish_workflow.yaml@main
    with:
      git_push_branch: main
      git_push: true
    secrets:
      token: ${{ secrets.ELEVATED_TOKEN }}

  rebase_dev:
    name: Write changes to dev branch
    needs: [api-guard]
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{secrets.ELEVATED_TOKEN}}

      - name: Setup Git User
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "gh-actions@merckgroup.com"

      - name: Update Test Branch
        run: |
          git checkout main
          git fetch origin
          git checkout dev
          git pull
          git merge origin/main
          git push origin dev
