name: Dev - 🚧 publish package

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+-[0-9]+"

jobs:
  publish:
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    environment: "pub.dev"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{secrets.ELEVATED_TOKEN}}

      - name: Publish mtrust_sec_kit
        uses: emdgroup/mtrust-urp/.github/actions/publish-pub-dev@main
        with:
          directory: "."
          publish_mode: --force
